// Auto-generated by process_anims.sh

#include "common-chax.h"
#include "KSDefinitions.h"

#define ITYPE_KNIFE ITYPE_LIGHT

const struct BattleAnimDef ADVENTURER_F_REF[] = {
	{ .wtype = 0x0100 | ITYPE_BOW, .index = ADVENTURER_F_BOW },
	{ .wtype = 0x0100 | ITYPE_STAFF, .index = ADVENTURER_F_STAFF },
	{ .wtype = 0x0100 | ITYPE_ITEM, .index = ADVENTURER_F_UNARMED },
	{ 0 }
};

const struct BattleAnimDef ADVENTURER_M_REF[] = {
	{ .wtype = 0x0100 | ITYPE_BOW, .index = ADVENTURER_M_BOW },
	{ .wtype = 0x0100 | ITYPE_STAFF, .index = ADVENTURER_M_STAFF },
	{ .wtype = 0x0100 | ITYPE_ITEM, .index = ADVENTURER_M_UNARMED },
	{ 0 }
};

const struct BattleAnimDef ARCHER_F_REF[] = {
	{ .wtype = 0x0100 | ITYPE_BOW, .index = ARCHER_F_BOW },
	{ .wtype = 0x0100 | ITYPE_ITEM, .index = ARCHER_F_UNARMED },
	{ 0 }
};

const struct BattleAnimDef ARCHER_M_REF[] = {
	{ .wtype = 0x0100 | ITYPE_BOW, .index = ARCHER_M_BOW },
	{ .wtype = 0x0100 | ITYPE_ITEM, .index = ARCHER_M_UNARMED },
	{ 0 }
};

const struct BattleAnimDef AXECAV_F_REF[] = {
	{ .wtype = 0x0100 | ITYPE_AXE, .index = AXECAV_F_AXE },
	{ .wtype = ITEM_AXE_HANDAXE, .index = AXECAV_F_HANDAXE },
	{ .wtype = ITEM_AXE_TOMAHAWK, .index = AXECAV_F_HANDAXE },
	{ .wtype = 0x0100 | ITYPE_ITEM, .index = AXECAV_F_UNARMED },
	{ 0 }
};

const struct BattleAnimDef AXECAV_M_REF[] = {
	{ .wtype = 0x0100 | ITYPE_AXE, .index = AXECAV_M_AXE },
	{ .wtype = ITEM_AXE_HANDAXE, .index = AXECAV_M_HANDAXE },
	{ .wtype = ITEM_AXE_TOMAHAWK, .index = AXECAV_M_HANDAXE },
	{ .wtype = 0x0100 | ITYPE_ITEM, .index = AXECAV_M_UNARMED },
	{ 0 }
};

const struct BattleAnimDef FIGHTER_M_REF[] = {
	{ .wtype = 0x0100 | ITYPE_AXE, .index = FIGHTER_M_AXE },
	{ .wtype = ITEM_AXE_HANDAXE, .index = FIGHTER_M_HANDAXE },
	{ .wtype = ITEM_AXE_TOMAHAWK, .index = FIGHTER_M_HANDAXE },
	{ .wtype = 0x0100 | ITYPE_ITEM, .index = FIGHTER_M_UNARMED },
	{ 0 }
};

const struct BattleAnimDef MAGE_F_REF[] = {
	{ .wtype = 0x0100 | ITYPE_ANIMA, .index = MAGE_F_MAGIC },
	{ .wtype = 0x0100 | ITYPE_DARK, .index = MAGE_F_MAGIC },
	{ .wtype = 0x0100 | ITYPE_STAFF, .index = MAGE_F_MAGIC },
	{ 0 }
};

const struct BattleAnimDef MAGE_M_REF[] = {
	{ .wtype = 0x0100 | ITYPE_ANIMA, .index = MAGE_M_MAGIC },
	{ .wtype = 0x0100 | ITYPE_DARK, .index = MAGE_M_MAGIC },
	{ .wtype = 0x0100 | ITYPE_STAFF, .index = MAGE_M_MAGIC },
	{ 0 }
};

const struct BattleAnimDef NINJA_F_REF[] = { { .wtype = 0x0100 | ITYPE_KNIFE,
					       .index = NINJA_F_KNIFE },
					     { 0 } };

const struct BattleAnimDef NINJA_M_REF[] = { { .wtype = 0x0100 | ITYPE_KNIFE,
					       .index = NINJA_M_KNIFE },
					     { 0 } };

const struct BattleAnimDef OUTLAW_F_REF[] = {
	{ .wtype = 0x0100 | ITYPE_BOW, .index = OUTLAW_F_BOW },
	{ .wtype = 0x0100 | ITYPE_ITEM, .index = OUTLAW_F_UNARMED },
	{ 0 }
};

const struct BattleAnimDef OUTLAW_M_REF[] = {
	{ .wtype = 0x0100 | ITYPE_BOW, .index = OUTLAW_M_BOW },
	{ .wtype = 0x0100 | ITYPE_ITEM, .index = OUTLAW_M_UNARMED },
	{ 0 }
};

const struct BattleAnimDef PRINCESS_F_REF[] = {
	{ .wtype = 0x0100 | ITYPE_SWORD, .index = PRINCESS_F_SWORD },
	{ .wtype = 0x0100 | ITYPE_ITEM, .index = PRINCESS_F_UNARMED },
	{ 0 }
};

const struct BattleAnimDef SOLDIER_F_REF[] = {
	{ .wtype = 0x0100 | ITYPE_LANCE, .index = SOLDIER_F_LANCE },
	{ .wtype = 0x0100 | ITYPE_ITEM, .index = SOLDIER_F_UNARMED },
	{ 0 }
};

const struct BattleAnimDef SOLDIER_M_REF[] = {
	{ .wtype = 0x0100 | ITYPE_LANCE, .index = SOLDIER_M_LANCE },
	{ .wtype = 0x0100 | ITYPE_ITEM, .index = SOLDIER_M_UNARMED },
	{ 0 }
};

const struct BattleAnimDef SWORDFIGHTER_F_REF[] = {
	{ .wtype = 0x0100 | ITYPE_SWORD, .index = SWORDFIGHTER_F_SWORD },
	{ .wtype = 0x0100 | ITYPE_ITEM, .index = SWORDFIGHTER_F_UNARMED },
	{ 0 }
};

const struct BattleAnimDef SWORDFIGHTER_M_REF[] = {
	{ .wtype = 0x0100 | ITYPE_SWORD, .index = SWORDFIGHTER_M_SWORD },
	{ .wtype = 0x0100 | ITYPE_ITEM, .index = SWORDFIGHTER_M_UNARMED },
	{ 0 }
};
