// Auto generated by process_map_sprites.sh

enum ClassCardDefinitions {
    AXE_CAVALIER_CARD = 114,
    FIGHTER_CARD = 115,
    NINJA_CARD = 116,
    LANCE_CAVALIER_CARD = 117,
    ARCHER_CARD = 118,
    MONK_CARD = 119,
    SWORDFIGHTER_CARD = 120,
    OUTLAW_CARD = 121,
    SOLDIER_CARD = 122,
};
