// Auto-generated by process_anims.sh

#pragma once
#define ITYPE_KNIFE ITYPE_LIGHT
enum AnimationTableIndex {
    ADVENTURER_F_BOW = 1,
    ADVENTURER_F_STAFF = 2,
    ADVENTURER_F_UNARMED = 3,
    ADVENTURER_M_BOW = 4,
    ADVENTURER_M_STAFF = 5,
    ADVENTURER_M_UNARMED = 6,
    ARMOR_U_AXE = 7,
    ARMOR_U_HANDAXE = 8,
    ARMOR_U_LANCE = 9,
    ARMOR_U_SWORD = 10,
    ARMOR_U_UNARMED = 11,
    BALLISTA_U_BOW = 12,
    CANTOR_M_MAGIC = 13,
    CANTOR_M_STAFF = 14,
    CAVALIER_F_AXE = 15,
    CAVALIER_F_HANDAXE = 16,
    CAVALIER_F_LANCE = 17,
    CAVALIER_F_SWORD = 18,
    CAVALIER_F_UNARMED = 19,
    CAVALIER_M_AXE = 20,
    CAVALIER_M_HANDAXE = 21,
    CAVALIER_M_LANCE = 22,
    CAVALIER_M_SWORD = 23,
    CAVALIER_M_UNARMED = 24,
    MAGE_M_MAGIC = 28,
    MILITIA_F_LANCE = 29,
    MILITIA_F_UNARMED = 30,
    MILITIA_M_LANCE = 31,
    MILITIA_M_UNARMED = 35,
    NINJA_F_KNIFE = 36,
    NINJA_M_KNIFE = 37,
    NOMAD_F_BOW = 42,
    NOMAD_F_UNARMED = 43,
    NOMAD_M_BOW = 44,
    NOMAD_M_UNARMED = 45,
    OUTLAW_F_BOW = 46,
    OUTLAW_F_UNARMED = 47,
    OUTLAW_M_BOW = 48,
    OUTLAW_M_UNARMED = 49,
    PEGASUS_F_LANCE = 50,
    PEGASUS_F_SWORD = 51,
    PEGASUS_F_UNARMED = 52,
    PRINCESS_F_SWORD = 53,
    PRINCESS_F_UNARMED = 54,
    SOLDIER_F_LANCE = 55,
    SOLDIER_F_UNARMED = 56,
    SOLDIER_M_LANCE = 57,
    SOLDIER_M_UNARMED = 58,
    SWORDFIGHTER_F_SWORD = 59,
    SWORDFIGHTER_F_UNARMED = 60,
    SWORDFIGHTER_M_SWORD = 61,
    SWORDFIGHTER_M_UNARMED = 62,
    UMBRALBISHOP_F_MAGIC = 63,
    UMBRALBISHOP_F_STAFF = 64,
    WYVERNRIDER_U_AXE = 65,
    WYVERNRIDER_U_HANDAXE = 66,
    WYVERNRIDER_U_UNARMED = 67,
    ARCHER_F_BOW = 40,
    FIGHTER_M_AXE = 25,
    ARCHER_M_UNARMED = 39,
    BRIGAND_M_HANDAXE = 33,
    MAGE_F_MAGIC = 108,
    FIGHTER_M_HANDAXE = 26,
    BRIGAND_M_AXE = 32,
    UMBRALBISHOP_M_MAGIC = 123,
    FIGHTER_M_UNARMED = 27,
    ARCHER_F_UNARMED = 41,
    ARCHER_M_BOW = 38,
    BRIGAND_M_UNARMED = 34,
};
extern const struct BattleAnimDef ADVENTURER_F_REF[];
extern const struct BattleAnimDef ADVENTURER_M_REF[];
extern const struct BattleAnimDef ARCHER_F_REF[];
extern const struct BattleAnimDef ARCHER_M_REF[];
extern const struct BattleAnimDef ARMOR_U_REF[];
extern const struct BattleAnimDef BALLISTA_U_REF[];
extern const struct BattleAnimDef BRIGAND_M_REF[];
extern const struct BattleAnimDef CANTOR_M_REF[];
extern const struct BattleAnimDef CAVALIER_F_REF[];
extern const struct BattleAnimDef CAVALIER_M_REF[];
extern const struct BattleAnimDef FIGHTER_M_REF[];
extern const struct BattleAnimDef MAGE_F_REF[];
extern const struct BattleAnimDef MAGE_M_REF[];
extern const struct BattleAnimDef MILITIA_F_REF[];
extern const struct BattleAnimDef MILITIA_M_REF[];
extern const struct BattleAnimDef NINJA_F_REF[];
extern const struct BattleAnimDef NINJA_M_REF[];
extern const struct BattleAnimDef NOMAD_F_REF[];
extern const struct BattleAnimDef NOMAD_M_REF[];
extern const struct BattleAnimDef OUTLAW_F_REF[];
extern const struct BattleAnimDef OUTLAW_M_REF[];
extern const struct BattleAnimDef PEGASUS_F_REF[];
extern const struct BattleAnimDef PRINCESS_F_REF[];
extern const struct BattleAnimDef SOLDIER_F_REF[];
extern const struct BattleAnimDef SOLDIER_M_REF[];
extern const struct BattleAnimDef SWORDFIGHTER_F_REF[];
extern const struct BattleAnimDef SWORDFIGHTER_M_REF[];
extern const struct BattleAnimDef UMBRALBISHOP_F_REF[];
extern const struct BattleAnimDef UMBRALBISHOP_M_REF[];
extern const struct BattleAnimDef WYVERNRIDER_U_REF[];
