// Auto-generated by process_anims.sh

#include "common-chax.h"
#include "KSDefinitions.h"

const struct BattleAnimDef ADVENTURER_F_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_BOW,
        .index = (u16) ADVENTURER_F_BOW
    },
    {
        .wtype = 0x0100 | ITYPE_STAFF,
        .index = (u16) ADVENTURER_F_STAFF
    },
    {
        .wtype = 0x0100 | ITYPE_ITEM,
        .index = (u16) ADVENTURER_F_UNARMED
    },
    {0}
};

const struct BattleAnimDef ADVENTURER_M_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_BOW,
        .index = (u16) ADVENTURER_M_BOW
    },
    {
        .wtype = 0x0100 | ITYPE_STAFF,
        .index = (u16) ADVENTURER_M_STAFF
    },
    {
        .wtype = 0x0100 | ITYPE_ITEM,
        .index = (u16) ADVENTURER_M_UNARMED
    },
    {0}
};

const struct BattleAnimDef ARMOR_U_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_AXE,
        .index = (u16) ARMOR_U_AXE
    },
    {
        .wtype = ITEM_AXE_HANDAXE,
        .index = (u16) ARMOR_U_HANDAXE
    },
    {
        .wtype = ITEM_AXE_TOMAHAWK,
        .index = (u16) ARMOR_U_HANDAXE
    },
    {
        .wtype = 0x0100 | ITYPE_LANCE,
        .index = (u16) ARMOR_U_LANCE
    },
    {
        .wtype = 0x0100 | ITYPE_SWORD,
        .index = (u16) ARMOR_U_SWORD
    },
    {
        .wtype = 0x0100 | ITYPE_ITEM,
        .index = (u16) ARMOR_U_UNARMED
    },
    {0}
};

const struct BattleAnimDef BALLISTA_U_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_BOW,
        .index = (u16) BALLISTA_U_BOW
    },
    {0}
};

const struct BattleAnimDef CANTOR_M_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_ANIMA,
        .index = (u16) CANTOR_M_MAGIC
    },
    {
        .wtype = 0x0100 | ITYPE_DARK,
        .index = (u16) CANTOR_M_MAGIC
    },
    {
        .wtype = 0x0100 | ITYPE_STAFF,
        .index = (u16) CANTOR_M_MAGIC
    },
    {
        .wtype = 0x0100 | ITYPE_STAFF,
        .index = (u16) CANTOR_M_STAFF
    },
    {0}
};

const struct BattleAnimDef CAVALIER_F_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_AXE,
        .index = (u16) CAVALIER_F_AXE
    },
    {
        .wtype = ITEM_AXE_HANDAXE,
        .index = (u16) CAVALIER_F_HANDAXE
    },
    {
        .wtype = ITEM_AXE_TOMAHAWK,
        .index = (u16) CAVALIER_F_HANDAXE
    },
    {
        .wtype = 0x0100 | ITYPE_LANCE,
        .index = (u16) CAVALIER_F_LANCE
    },
    {
        .wtype = 0x0100 | ITYPE_SWORD,
        .index = (u16) CAVALIER_F_SWORD
    },
    {
        .wtype = 0x0100 | ITYPE_ITEM,
        .index = (u16) CAVALIER_F_UNARMED
    },
    {0}
};

const struct BattleAnimDef CAVALIER_M_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_AXE,
        .index = (u16) CAVALIER_M_AXE
    },
    {
        .wtype = ITEM_AXE_HANDAXE,
        .index = (u16) CAVALIER_M_HANDAXE
    },
    {
        .wtype = ITEM_AXE_TOMAHAWK,
        .index = (u16) CAVALIER_M_HANDAXE
    },
    {
        .wtype = 0x0100 | ITYPE_LANCE,
        .index = (u16) CAVALIER_M_LANCE
    },
    {
        .wtype = 0x0100 | ITYPE_SWORD,
        .index = (u16) CAVALIER_M_SWORD
    },
    {
        .wtype = 0x0100 | ITYPE_ITEM,
        .index = (u16) CAVALIER_M_UNARMED
    },
    {0}
};

const struct BattleAnimDef MAGE_M_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_ANIMA,
        .index = (u16) MAGE_M_MAGIC
    },
    {
        .wtype = 0x0100 | ITYPE_DARK,
        .index = (u16) MAGE_M_MAGIC
    },
    {
        .wtype = 0x0100 | ITYPE_STAFF,
        .index = (u16) MAGE_M_MAGIC
    },
    {0}
};

const struct BattleAnimDef MILITIA_F_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_LANCE,
        .index = (u16) MILITIA_F_LANCE
    },
    {
        .wtype = 0x0100 | ITYPE_ITEM,
        .index = (u16) MILITIA_F_UNARMED
    },
    {0}
};

const struct BattleAnimDef MILITIA_M_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_LANCE,
        .index = (u16) MILITIA_M_LANCE
    },
    {
        .wtype = 0x0100 | ITYPE_ITEM,
        .index = (u16) MILITIA_M_UNARMED
    },
    {0}
};

const struct BattleAnimDef NINJA_F_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_KNIFE,
        .index = (u16) NINJA_F_KNIFE
    },
    {0}
};

const struct BattleAnimDef NINJA_M_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_KNIFE,
        .index = (u16) NINJA_M_KNIFE
    },
    {0}
};

const struct BattleAnimDef NOMAD_F_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_BOW,
        .index = (u16) NOMAD_F_BOW
    },
    {
        .wtype = 0x0100 | ITYPE_ITEM,
        .index = (u16) NOMAD_F_UNARMED
    },
    {0}
};

const struct BattleAnimDef NOMAD_M_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_BOW,
        .index = (u16) NOMAD_M_BOW
    },
    {
        .wtype = 0x0100 | ITYPE_ITEM,
        .index = (u16) NOMAD_M_UNARMED
    },
    {0}
};

const struct BattleAnimDef OUTLAW_F_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_BOW,
        .index = (u16) OUTLAW_F_BOW
    },
    {
        .wtype = 0x0100 | ITYPE_ITEM,
        .index = (u16) OUTLAW_F_UNARMED
    },
    {0}
};

const struct BattleAnimDef OUTLAW_M_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_BOW,
        .index = (u16) OUTLAW_M_BOW
    },
    {
        .wtype = 0x0100 | ITYPE_ITEM,
        .index = (u16) OUTLAW_M_UNARMED
    },
    {0}
};

const struct BattleAnimDef PEGASUS_F_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_LANCE,
        .index = (u16) PEGASUS_F_LANCE
    },
    {
        .wtype = 0x0100 | ITYPE_SWORD,
        .index = (u16) PEGASUS_F_SWORD
    },
    {
        .wtype = 0x0100 | ITYPE_ITEM,
        .index = (u16) PEGASUS_F_UNARMED
    },
    {0}
};

const struct BattleAnimDef PRINCESS_F_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_SWORD,
        .index = (u16) PRINCESS_F_SWORD
    },
    {
        .wtype = 0x0100 | ITYPE_ITEM,
        .index = (u16) PRINCESS_F_UNARMED
    },
    {0}
};

const struct BattleAnimDef SOLDIER_F_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_LANCE,
        .index = (u16) SOLDIER_F_LANCE
    },
    {
        .wtype = 0x0100 | ITYPE_ITEM,
        .index = (u16) SOLDIER_F_UNARMED
    },
    {0}
};

const struct BattleAnimDef SOLDIER_M_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_LANCE,
        .index = (u16) SOLDIER_M_LANCE
    },
    {
        .wtype = 0x0100 | ITYPE_ITEM,
        .index = (u16) SOLDIER_M_UNARMED
    },
    {0}
};

const struct BattleAnimDef SWORDFIGHTER_F_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_SWORD,
        .index = (u16) SWORDFIGHTER_F_SWORD
    },
    {
        .wtype = 0x0100 | ITYPE_ITEM,
        .index = (u16) SWORDFIGHTER_F_UNARMED
    },
    {0}
};

const struct BattleAnimDef SWORDFIGHTER_M_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_SWORD,
        .index = (u16) SWORDFIGHTER_M_SWORD
    },
    {
        .wtype = 0x0100 | ITYPE_ITEM,
        .index = (u16) SWORDFIGHTER_M_UNARMED
    },
    {0}
};

const struct BattleAnimDef UMBRALBISHOP_F_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_ANIMA,
        .index = (u16) UMBRALBISHOP_F_MAGIC
    },
    {
        .wtype = 0x0100 | ITYPE_DARK,
        .index = (u16) UMBRALBISHOP_F_MAGIC
    },
    {
        .wtype = 0x0100 | ITYPE_STAFF,
        .index = (u16) UMBRALBISHOP_F_MAGIC
    },
    {
        .wtype = 0x0100 | ITYPE_STAFF,
        .index = (u16) UMBRALBISHOP_F_STAFF
    },
    {0}
};

const struct BattleAnimDef WYVERNRIDER_U_REF[] = 
{
    {
        .wtype = 0x0100 | ITYPE_AXE,
        .index = (u16) WYVERNRIDER_U_AXE
    },
    {
        .wtype = ITEM_AXE_HANDAXE,
        .index = (u16) WYVERNRIDER_U_HANDAXE
    },
    {
        .wtype = ITEM_AXE_TOMAHAWK,
        .index = (u16) WYVERNRIDER_U_HANDAXE
    },
    {
        .wtype = 0x0100 | ITYPE_ITEM,
        .index = (u16) WYVERNRIDER_U_UNARMED
    },
    {0}
};

