// Auto-generated by process_anims.sh

#pragma once
#define ITYPE_KNIFE ITYPE_LIGHT

enum AnimationTableIndex {
    ADVENTURER_F_BOW = 1,
    ADVENTURER_F_STAFF = 2,
    ADVENTURER_F_UNARMED = 3,
    ADVENTURER_M_BOW = 4,
    ADVENTURER_M_STAFF = 5,
    ADVENTURER_M_UNARMED = 6,
    ARCHER_F_BOW = 7,
    ARCHER_F_UNARMED = 8,
    ARCHER_M_BOW = 9,
    ARCHER_M_UNARMED = 10,
    AXECAV_F_AXE = 11,
    AXECAV_F_HANDAXE = 12,
    AXECAV_F_UNARMED = 13,
    AXECAV_M_AXE = 14,
    AXECAV_M_HANDAXE = 15,
    AXECAV_M_UNARMED = 16,
    FIGHTER_M_AXE = 17,
    FIGHTER_M_HANDAXE = 18,
    FIGHTER_M_UNARMED = 19,
    MAGE_F_MAGIC = 20,
    MAGE_M_MAGIC = 21,
    NINJA_F_KNIFE = 22,
    NINJA_M_KNIFE = 23,
    OUTLAW_F_BOW = 24,
    OUTLAW_F_UNARMED = 25,
    OUTLAW_M_BOW = 26,
    OUTLAW_M_UNARMED = 27,
    PRINCESS_F_SWORD = 28,
    PRINCESS_F_UNARMED = 29,
    SOLDIER_F_LANCE = 30,
    SOLDIER_F_UNARMED = 31,
    SOLDIER_M_LANCE = 32,
    SOLDIER_M_UNARMED = 33,
    SWORDFIGHTER_F_SWORD = 34,
    SWORDFIGHTER_F_UNARMED = 35,
    SWORDFIGHTER_M_SWORD = 36,
    SWORDFIGHTER_M_UNARMED = 37,
};

extern const struct BattleAnimDef ADVENTURER_F_REF[];
extern const struct BattleAnimDef ADVENTURER_M_REF[];
extern const struct BattleAnimDef ARCHER_F_REF[];
extern const struct BattleAnimDef ARCHER_M_REF[];
extern const struct BattleAnimDef AXECAV_F_REF[];
extern const struct BattleAnimDef AXECAV_M_REF[];
extern const struct BattleAnimDef FIGHTER_M_REF[];
extern const struct BattleAnimDef MAGE_F_REF[];
extern const struct BattleAnimDef MAGE_M_REF[];
extern const struct BattleAnimDef NINJA_F_REF[];
extern const struct BattleAnimDef NINJA_M_REF[];
extern const struct BattleAnimDef OUTLAW_F_REF[];
extern const struct BattleAnimDef OUTLAW_M_REF[];
extern const struct BattleAnimDef PRINCESS_F_REF[];
extern const struct BattleAnimDef SOLDIER_F_REF[];
extern const struct BattleAnimDef SOLDIER_M_REF[];
extern const struct BattleAnimDef SWORDFIGHTER_F_REF[];
extern const struct BattleAnimDef SWORDFIGHTER_M_REF[];
