#!/bin/bash

# Define the subdirectory containing the PNG files
SMS_SUBDIRECTORY="SMS"
MMS_SUBDIRECTORY="MMS"
BUILD_SUBDIRECTORY="Build"

# Define the program to process the PNG files
PROGRAM="../../Tools/EventAssembler/Tools/Png2Dmp"

# Define the input text file
INPUT_FILE="class_info.txt"

# Define the output event files
OUTPUT_SPRITE_INSTALLER="MapSpriteData.event"
OUTPUT_TABLE_INSTALLER="MapSpriteTable.event"

# Check if the subdirectory exists
if [[ ! -d "$SMS_SUBDIRECTORY" ]]; then
    echo "Error: Subdirectory '$SMS_SUBDIRECTORY' not found."
    exit 1
fi

# Check if the program exists and is executable
if [[ ! -x "$PROGRAM" ]]; then
    echo "Error: $PROGRAM is not executable or does not exist"
    exit 1
fi

# Process PNG files
find "$SMS_SUBDIRECTORY" "$MMS_SUBDIRECTORY" -type f -name "*.png" -print0 | while IFS= read -r -d $'\0' file; do
    echo "Processing: $file"
    filename=$(basename "$file") # Get the full filename (e.g., image.png)
    directory=$(basename "$(dirname "$file")") # Get the directory name
    output_file="${directory}_${filename%.png}.dmp" # Remove the .png extension
    "$PROGRAM" "$file" --lz77 -o "$BUILD_SUBDIRECTORY/$output_file"
    if [[ $? -ne 0 ]]; then
        echo "Error: $PROGRAM failed to process $file"
    fi
done

echo "Finished processing all PNG files."

# Process the input text file and generate the event file
if [[ ! -f "$INPUT_FILE" ]]; then
    echo "Error: Input file '$INPUT_FILE' not found."
    exit 1
fi


# Create or overwrite the output files
> "$OUTPUT_SPRITE_INSTALLER"
> "$OUTPUT_TABLE_INSTALLER"

echo "// Auto generated by process_map_sprites.sh" >> "$OUTPUT_SPRITE_INSTALLER"
echo "" >> "$OUTPUT_SPRITE_INSTALLER"

echo "// Auto generated by process_map_sprites.sh" >> "$OUTPUT_TABLE_INSTALLER"
echo "" >> "$OUTPUT_TABLE_INSTALLER"
echo "PUSH" >> "$OUTPUT_TABLE_INSTALLER"
echo "" >> "$OUTPUT_TABLE_INSTALLER"

index=0

while IFS=$' \t' read -r class sms_size ptr_data; do
    # Generate the portrait labels and includes

    sms_def="${class}_SMS"
    mms_def="${class}_MMS"

    echo "// $class" >> $OUTPUT_SPRITE_INSTALLER
    echo "ALIGN 4" >> $OUTPUT_SPRITE_INSTALLER
    echo "${sms_def}:" >> $OUTPUT_SPRITE_INSTALLER
    echo "#incbin Build/SMS_${class}.dmp" >> $OUTPUT_SPRITE_INSTALLER
    echo "" >> $OUTPUT_SPRITE_INSTALLER
    echo "ALIGN 4" >> $OUTPUT_SPRITE_INSTALLER
    echo "${mms_def}:" >> $OUTPUT_SPRITE_INSTALLER
    echo "#incbin Build/MMS_${class}.dmp" >> $OUTPUT_SPRITE_INSTALLER
    echo "" >> $OUTPUT_SPRITE_INSTALLER
    echo "" >> $OUTPUT_SPRITE_INSTALLER

    # Generate the table installer
    echo "// $class" >> $OUTPUT_TABLE_INSTALLER
    echo "SetSMS($index, $sms_size, $sms_def)" >> $OUTPUT_TABLE_INSTALLER
    echo "SetMMS($index, $mms_def, $ptr_data)" >> $OUTPUT_TABLE_INSTALLER
    echo "" >> $OUTPUT_TABLE_INSTALLER

    # Increment the variable
    ((index++))

done < "$INPUT_FILE"

echo "POP" >> "$OUTPUT_TABLE_INSTALLER"

echo "Generated '$OUTPUT_SPRITE_INSTALLER' and '$OUTPUT_TABLE_INSTALLER'."

exit 0