// Auto generated by process_portraits.sh

#pragma once

enum PortraitDefinitions
{
    PORTRAIT_AUDREY_ID = 2,
    PORTRAIT_WESLEY_ID = 3,
    PORTRAIT_OSBORNE_ID = 4,
    PORTRAIT_ELAINE_ID = 5,
    PORTRAIT_SURGE_ID = 6,
    PORTRAIT_CORDELL_ID = 7,
    PORTRAIT_LIEV_ID = 8,
    PORTRAIT_JYRI_ID = 9,
    PORTRAIT_OSMA_ID = 10,
    PORTRAIT_GLOVE_ID = 11,
    PORTRAIT_FESTER_ID = 12,
};
