#!/bin/bash

# Made using Gemini

# Define the subdirectory containing the PNG files
SUBDIRECTORY="./PortraitData"

# Define the program to process the PNG files
PROGRAM="../../Tools/EventAssembler/Tools/PortraitFormatter"

# Define the input text file
INPUT_FILE="portrait_config.txt"

# Define the output event file
OUTPUT_EVENT_FILE="MasterPortraitInstaller.event"
OUTPUT_HEADER_FILE="PortraitID.h"
OUTPUT_TEXT_DEFS="../../Contents/Texts/textdefs.txt"
INPUT_TEXT_DEFS_NO_PORTRAIT="../../Contents/Texts/textdefs_no_portraits.txt"

# Check if the subdirectory exists
if [[ ! -d "$SUBDIRECTORY" ]]; then
    echo "Error: Subdirectory '$SUBDIRECTORY' not found."
    exit 1
fi

# Check if the program exists and is executable
if [[ ! -x "$PROGRAM" ]]; then
    echo "Error: $PROGRAM is not executable or does not exist"
    exit 1
fi

# Process PNG files
find "$SUBDIRECTORY" -type f -name "*.png" -print0 | while IFS= read -r -d $'\0' file; do
    echo "Processing: $file"
    "$PROGRAM" "$file"
    if [[ $? -ne 0 ]]; then
        echo "Error: $PROGRAM failed to process $file"
    fi
done

echo "Finished processing all PNG files."

# Process the input text file and generate the event file
if [[ ! -f "$INPUT_FILE" ]]; then
    echo "Error: Input file '$INPUT_FILE' not found."
    exit 1
fi

# Initialize the mug entry index
mug_entry_index=2

# Create or overwrite the output files
> "$OUTPUT_EVENT_FILE"
> "$OUTPUT_HEADER_FILE"
> "$OUTPUT_TEXT_DEFS"

echo "// Auto generated by process_portraits.sh" >> "$OUTPUT_EVENT_FILE"
echo "" >> "$OUTPUT_EVENT_FILE"

echo "// Auto generated by process_portraits.sh" >> "$OUTPUT_HEADER_FILE"
echo "" >> "$OUTPUT_HEADER_FILE"
echo "#pragma once" >> "$OUTPUT_HEADER_FILE"
echo "" >> "$OUTPUT_HEADER_FILE"
echo "enum PortraitDefinitions" >> "$OUTPUT_HEADER_FILE"
echo "{" >> "$OUTPUT_HEADER_FILE"

cat "$INPUT_TEXT_DEFS_NO_PORTRAIT" > "$OUTPUT_TEXT_DEFS"
echo "" >> "$OUTPUT_TEXT_DEFS"
echo "" >> "$OUTPUT_TEXT_DEFS"

while IFS=$' \t' read -r name a b c d; do
    # Generate the portrait labels and includes
    echo "// $name" >> "$OUTPUT_EVENT_FILE"
    echo "ALIGN 4" >> "$OUTPUT_EVENT_FILE"
    echo "${name}Portrait:" >> "$OUTPUT_EVENT_FILE"
    echo "#incbin \"$SUBDIRECTORY/${name}_mug.dmp\"" >> "$OUTPUT_EVENT_FILE"
    echo "#incbin \"$SUBDIRECTORY/${name}_frames.dmp\"" >> "$OUTPUT_EVENT_FILE"
    echo "#incbin \"$SUBDIRECTORY/${name}_palette.dmp\"" >> "$OUTPUT_EVENT_FILE"
    echo "#incbin \"$SUBDIRECTORY/${name}_minimug.dmp\"" >> "$OUTPUT_EVENT_FILE"
    hex_index=$(printf "0x%X" "$mug_entry_index")
    echo "setMugEntry($hex_index,${name}Portrait,$a,$b,$c,$d)" >> "$OUTPUT_EVENT_FILE"
    echo "" >> "$OUTPUT_EVENT_FILE"
    # Generate the header file info
    echo "    PORTRAIT_${name^^}_ID = $mug_entry_index," >> "$OUTPUT_HEADER_FILE"
    # Generate the text definition info
    echo "[Load$name] = 0x10, $hex_index, 0x1" >> "$OUTPUT_TEXT_DEFS"

    # Increment the mug entry index
    ((mug_entry_index++))
done < "$INPUT_FILE"

echo "};" >> "$OUTPUT_HEADER_FILE"

echo "Generated '$OUTPUT_EVENT_FILE', '$OUTPUT_HEADER_FILE', and '$OUTPUT_TEXT_DEFS'."

exit 0