#!/bin/bash

# Made using Gemeni

# Define subdirectories
subdirectories=(
  "Swords"
  "Lances"
  "Axes"
  "Bows"
  "Light"
  "Anima"
  "Misc"
)

# Output file names
OUTPUT_HEADER_FILE="ItemIDs.h"
OUTPUT_EVENT_DEFINITIONS_FILE="ItemIDs.event"
OUTPUT_MASTER_INSTALLER_FILE="MasterItemInstaller.event"

# Start generating the header file
echo "// Auto-generated by process_items.sh" > "$OUTPUT_HEADER_FILE"
echo "" >> "$OUTPUT_HEADER_FILE"
echo "enum ItemDefinitions" >> "$OUTPUT_HEADER_FILE"
echo "{" >> "$OUTPUT_HEADER_FILE"
echo "    ITEM_NONE," >> "$OUTPUT_HEADER_FILE"

# Start generating the ItemIDs.event file
echo "// Auto-generated by process_items.sh" > "$OUTPUT_EVENT_DEFINITIONS_FILE"
echo "" >> "$OUTPUT_EVENT_DEFINITIONS_FILE"

# Start generating master installer file
echo "// Auto-generated by process_items.sh" > "$OUTPUT_MASTER_INSTALLER_FILE"
echo "" >> "$OUTPUT_MASTER_INSTALLER_FILE"
echo "#include \"$OUTPUT_EVENT_DEFINITIONS_FILE\"" >> "$OUTPUT_MASTER_INSTALLER_FILE"
echo "" >> "$OUTPUT_MASTER_INSTALLER_FILE"
echo "PUSH" >> "$OUTPUT_MASTER_INSTALLER_FILE"
echo "    ORG \$809B10 + \$24" >> "$OUTPUT_MASTER_INSTALLER_FILE"

# Initialize ID counter
id_counter=1

# Process each subdirectory
for subdir in "${subdirectories[@]}"; do
  echo "    // $subdir" >> "$OUTPUT_HEADER_FILE"

  # Create installer event file
  installer_event_file="$subdir/${subdir}Installer.event"
  echo "" > "$installer_event_file"

  # Add to the master installer file
  echo "    #include \"$installer_event_file\"" >> "$OUTPUT_MASTER_INSTALLER_FILE"

  # Process each C file in the subdirectory
  file_count=0
  for file in "$subdir"/*.c; do
    if [[ -f "$file" ]]; then
      filename=$(basename "$file")
      filename_no_extension="${filename%.c}"
      enum_name="ITEM_${filename_no_extension^^}" # Uppercase for enum
      define_name="ITEM_${filename_no_extension^^}" # Uppercase for define

      echo "    $enum_name," >> "$OUTPUT_HEADER_FILE"
      echo "#include ${filename_no_extension}.lyn.event" >> "$installer_event_file"
      echo "#define $define_name $id_counter" >> "$OUTPUT_EVENT_DEFINITIONS_FILE"
      file_count=$((file_count + 1))
      id_counter=$((id_counter + 1))
    fi
  done
  if [[ $file_count -eq 0 ]]; then
      echo "    // No Items in $subdir" >> "$OUTPUT_HEADER_FILE"
  fi
done

# Finish generating the header/master installer file
echo "POP" >> "$OUTPUT_MASTER_INSTALLER_FILE"
echo "};" >> "$OUTPUT_HEADER_FILE"

echo "Header file '$OUTPUT_HEADER_FILE', ItemIDs.event, and installer event files created."