#!/bin/bash

# Made using Gemeni

# Class data location
subdir="ClassData"

# Output file names
OUTPUT_HEADER_FILE="ClassIDs.h"
OUTPUT_EVENT_DEFINITIONS_FILE="ClassIDs.event"
OUTPUT_MASTER_INSTALLER_FILE="MasterClassInstaller.event"

# Start generating the header file
echo "// Auto-generated by process_classes.sh" > "$OUTPUT_HEADER_FILE"
echo "" >> "$OUTPUT_HEADER_FILE"
echo "enum ClassDefinitions" >> "$OUTPUT_HEADER_FILE"
echo "{" >> "$OUTPUT_HEADER_FILE"
echo "    CLASS_NONE," >> "$OUTPUT_HEADER_FILE"

# Start generating the ClassIDs.event file
echo "// Auto-generated by process_classes.sh" > "$OUTPUT_EVENT_DEFINITIONS_FILE"
echo "" >> "$OUTPUT_EVENT_DEFINITIONS_FILE"

# Start generating master installer file
echo "// Auto-generated by process_classes.sh" > "$OUTPUT_MASTER_INSTALLER_FILE"
echo "" >> "$OUTPUT_MASTER_INSTALLER_FILE"
echo "#include \"$OUTPUT_EVENT_DEFINITIONS_FILE\"" >> "$OUTPUT_MASTER_INSTALLER_FILE"
echo "" >> "$OUTPUT_MASTER_INSTALLER_FILE"
echo "PUSH" >> "$OUTPUT_MASTER_INSTALLER_FILE"
echo "    ORG \$807110 + \$54" >> "$OUTPUT_MASTER_INSTALLER_FILE"

# Initialize ID counter
id_counter=1

# Define the input file containing the list of filenames
INPUT_FILE_LIST="class_info.txt"

# Check if the input file exists
if [[ ! -f "$INPUT_FILE_LIST" ]]; then
  echo "Error: Input file '$INPUT_FILE_LIST' not found."
  exit 1
fi

# Read each line (filename) from the input file
while IFS=' ' read -r filename parameter; do
  # Construct the full path to the file
  file="$subdir/$filename.c"

  # Check if the file exists
  if [[ -f "$file" ]]; then
    filename=$(basename "$file")
    filename_no_extension="${filename%.c}"
    enum_name="CLASS_${filename_no_extension^^}" # Uppercase for enum

    echo "    $enum_name," >> "$OUTPUT_HEADER_FILE"
    echo "    #include \"ClassData/${filename_no_extension}.lyn.event\"" >> "$OUTPUT_MASTER_INSTALLER_FILE"
    echo "#define $enum_name $id_counter" >> "$OUTPUT_EVENT_DEFINITIONS_FILE"
    id_counter=$((id_counter + 1))
  else
    echo "Warning: File '$file' not found (listed in '$INPUT_FILE_LIST')."
  fi
done < "$INPUT_FILE_LIST"

# Finish generating the header/master installer file
echo "POP" >> "$OUTPUT_MASTER_INSTALLER_FILE"
echo "};" >> "$OUTPUT_HEADER_FILE"

cp "class_info.txt" "../../../Contents/MapSprites/class_info.txt"

echo "Header file '$OUTPUT_HEADER_FILE', ClassIDs.event, and installer event files created."